api_version: v1 #required

# Policies

# Global settings
settings: #required
  base_path: /api
  port: 3000

# Authentication configuration
authentication:
  jwt:
    secret: your_jwt_secret_key

# Authorization configuration
authorization:
  roles:
    - name: public
      permissions: [read]
    - name: user
      permissions: [read, write]
    - name: admin
      permissions: [read, write, admin]

# Rate Limiting configuration
rate_limiting:
  enabled: true
  max_requests: 5000
  interval: 1d

# Logging configuration
logging:
  format: combined
  log_level: debug
  file:
    enabled: true
    path: /logs/api-gateway.log

# Caching configuration
caching:
  client: redis
  default_ttl: 1000
  max_size: 1000

# Routes configuration
routes:
  - path: /public
    target: http://localhost:3003
    methods: [GET]
    authentication:
      type: none
    authorization:
      roles: [public]

  - path: /users
    target: http://localhost:3001
    methods: [GET, POST]
    authentication:
      type: none
      # audience: user-api
    authorization:
      roles: [user]

  - path: /
    target: http://localhost:3001
    methods: [GET]
    authentication:
      type: none
      # audience: user-api
    authorization:
      roles: [user]

  - path: /users/:id
    target: http://user-service:3001
    methods: [GET]
    authentication:
      type: jwt
      audience: user-api
    authorization:
      roles: [admin]
    # add more configurations as needed
